# Generated by Django 3.1.7 on 2021-03-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='middle_name',
            field=models.CharField(default=1, max_length=255, verbose_name='Отчество'),
            preserve_default=False,
        ),
    ]
