# Generated by Django 3.1.7 on 2021-03-13 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_price_x_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price_x_items',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Количество х цена'),
        ),
        migrations.CreateModel(
            name='OrderTotalPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая цена')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_total_price', to='orders.order')),
            ],
        ),
    ]
