# Generated by Django 3.1.5 on 2021-02-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210220_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='all_total_price',
            field=models.CharField(default=0, max_length=50, verbose_name='Самая общая цена'),
        ),
    ]
