# Generated by Django 3.1.5 on 2021-02-20 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_all_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='all_total_price',
        ),
    ]
