# Generated by Django 3.1.7 on 2021-03-13 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_orderitem_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertotalprice',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_total_price', to='orders.order'),
        ),
    ]
