# Generated by Django 3.1.5 on 2021-02-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210223_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='E-mail'),
            preserve_default=False,
        ),
    ]
