# Generated by Django 3.1.7 on 2021-03-14 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210313_1220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Элемент заказа', 'verbose_name_plural': 'Элементы заказа'},
        ),
        migrations.AlterModelOptions(
            name='ordertotalprice',
            options={'verbose_name': 'Общая цена заказа'},
        ),
    ]
