# Generated by Django 3.1.7 on 2021-03-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=1, upload_to='photos/%Y/%m', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
