# Generated by Django 3.1.7 on 2021-03-21 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210320_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_product', to='shop.product', verbose_name='Основной товар')),
                ('recommend_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recommend_product', to='shop.product', verbose_name='Рекомендованный товар')),
            ],
            options={
                'verbose_name': 'Рекомендованный товар',
                'verbose_name_plural': 'Рекомендованные товары',
            },
        ),
    ]
