# Generated by Django 3.1.7 on 2021-03-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_recommendproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_hit',
            field=models.BooleanField(default=False, verbose_name='ХИТ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=True, verbose_name='NEW'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_recommend',
            field=models.BooleanField(default=False, verbose_name='Рекомендованно'),
        ),
    ]
