# Generated by Django 3.1.7 on 2021-05-12 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210512_1640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopadminconst',
            options={'verbose_name': 'Константа', 'verbose_name_plural': 'Администрация констант сайта'},
        ),
        migrations.RemoveField(
            model_name='shopadminconst',
            name='EMAIL_ADMIN_CONFED',
        ),
        migrations.RemoveField(
            model_name='shopadminconst',
            name='EMAIL_ADMIN_PASSWORD_CONFED',
        ),
    ]
