# Generated by Django 3.1.7 on 2021-04-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_pagehit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageHit',
        ),
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
