# Generated by Django 3.1.7 on 2021-04-12 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_productsale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendproduct',
            name='recommend_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommend_product', to='shop.product', verbose_name='Рекомендованный товар'),
        ),
    ]
