# Generated by Django 3.1.7 on 2021-04-13 09:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20210412_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsale',
            name='sale',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Скидка, %'),
        ),
    ]
