# Generated by Django 3.1.7 on 2021-04-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20210413_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bonus_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Бонусные баллы'),
        ),
    ]
