# Generated by Django 3.1.7 on 2021-03-09 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_reg_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
