# Generated by Django 3.1.7 on 2021-03-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_middle_name'),
        ('user_reg_log', '0002_auto_20210309_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='orders',
            field=models.ManyToManyField(to='orders.Order', verbose_name='Заказы покупателя'),
        ),
    ]
