# Generated by Django 3.1.7 on 2021-03-11 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_price_x_items'),
        ('user_reg_log', '0003_profile_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='orders',
        ),
        migrations.AddField(
            model_name='profile',
            name='orders',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.PROTECT, to='orders.order', verbose_name='Заказы покупателя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
