# Generated by Django 3.1.7 on 2021-04-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_reg_log', '0004_auto_20210313_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='profile',
            name='bonus_points',
            field=models.IntegerField(blank=True, null=True, verbose_name='Бонусные баллы'),
        ),
    ]
