# Generated by Django 3.1.7 on 2021-04-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_reg_log', '0005_auto_20210414_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bonus_points',
            field=models.IntegerField(default=0, verbose_name='Бонусные баллы'),
        ),
    ]
