# Generated by Django 3.1.7 on 2021-05-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_shopadminconst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopadminconst',
            name='TIME_IS_NEW',
            field=models.PositiveIntegerField(verbose_name='Время (в часах) которое товар находится в статусе NEW'),
        ),
    ]
